apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fraud-detection

commonLabels:
  app: fraud-detection

resources:
- namespace.yaml
- pvc.yaml
- inference-deployment.yaml
- inference-service.yaml
- inference-route.yaml
